# =============================================================================
# Zsh Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Zsh Options
# -----------------------------------------------------------------------------
setopt AUTO_CD              # cd without typing cd
setopt AUTO_PUSHD           # Push directories to stack
setopt PUSHD_IGNORE_DUPS    # No duplicates in dir stack
setopt HIST_IGNORE_ALL_DUPS # No duplicate history entries
setopt HIST_SAVE_NO_DUPS    # Don't save duplicates
setopt SHARE_HISTORY        # Share history between sessions
setopt EXTENDED_GLOB        # Extended globbing

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# -----------------------------------------------------------------------------
# Completion
# -----------------------------------------------------------------------------
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# -----------------------------------------------------------------------------
# Antidote (Plugin Manager)
# -----------------------------------------------------------------------------
source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
antidote load

# -----------------------------------------------------------------------------
# fzf (Ctrl+T: files, Alt+C: cd)
# -----------------------------------------------------------------------------
source <(fzf --zsh)

# -----------------------------------------------------------------------------
# Atuin (Ctrl+R: history search, replaces fzf history)
# -----------------------------------------------------------------------------
eval "$(atuin init zsh)"

# -----------------------------------------------------------------------------
# Starship Prompt
# -----------------------------------------------------------------------------
eval "$(starship init zsh)"

# -----------------------------------------------------------------------------
# Vim mode indicator for WezTerm
# -----------------------------------------------------------------------------
function _update_vim_mode_wezterm() {
  local keymap="${1:-$VIM_MODE_KEYMAP}"
  local mode
  case $keymap in
    vicmd) mode="NORMAL" ;;
    viins|main) mode="INSERT" ;;
    visual) mode="VISUAL" ;;
    vline) mode="V-LINE" ;;
    replace) mode="REPLACE" ;;
    isearch) mode="SEARCH" ;;
    *) mode="INSERT" ;;
  esac
  # Send user var to WezTerm via OSC 1337
  printf '\033]1337;SetUserVar=VIM_MODE=%s\007' $(echo -n "$mode" | base64)
}
# Register callback for softmoth/zsh-vim-mode
vim_mode_keymap_funcs+=(_update_vim_mode_wezterm)
# Set initial mode
_update_vim_mode_wezterm viins

# -----------------------------------------------------------------------------
# PATH (auto-generated by tools)
# -----------------------------------------------------------------------------
# Homebrew (loaded in .zprofile)

# Rancher Desktop
export PATH="$HOME/.rd/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# Local bin
export PATH="$HOME/.local/bin:$PATH"
